// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAeIsRwJetF1p7M17exvXkkTSfPsMPVrQ',
    appId: '1:738145510517:web:1e661f67da7cab78cb043c',
    messagingSenderId: '738145510517',
    projectId: 'note-e1221',
    authDomain: 'note-e1221.firebaseapp.com',
    storageBucket: 'note-e1221.firebasestorage.app',
    measurementId: 'G-ZFY05GMVS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnAigJHmUuDAEvPI89TXg1qed8gn6RRIk',
    appId: '1:738145510517:android:36164249de7292e1cb043c',
    messagingSenderId: '738145510517',
    projectId: 'note-e1221',
    storageBucket: 'note-e1221.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVABOvel2OpkIt8ggflnBYys9SbXic0Gc',
    appId: '1:738145510517:ios:dd60a1d6db11750fcb043c',
    messagingSenderId: '738145510517',
    projectId: 'note-e1221',
    storageBucket: 'note-e1221.firebasestorage.app',
    iosBundleId: 'com.example.noteManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVABOvel2OpkIt8ggflnBYys9SbXic0Gc',
    appId: '1:738145510517:ios:dd60a1d6db11750fcb043c',
    messagingSenderId: '738145510517',
    projectId: 'note-e1221',
    storageBucket: 'note-e1221.firebasestorage.app',
    iosBundleId: 'com.example.noteManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAeIsRwJetF1p7M17exvXkkTSfPsMPVrQ',
    appId: '1:738145510517:web:cf44bff67feb6254cb043c',
    messagingSenderId: '738145510517',
    projectId: 'note-e1221',
    authDomain: 'note-e1221.firebaseapp.com',
    storageBucket: 'note-e1221.firebasestorage.app',
    measurementId: 'G-FV8059B6LJ',
  );
}
